sudo: required
services:
- docker

env:
  global:
  - BINTRAY_USER=vicamo
  - BINTRAY_REPO=ppa
  - BINTRAY_COMPONENT=contrib
  - BINTRAY_DESC="Personal Package Archive for Ubuntu-only dbus-cpp package"
  - DOCKER_EXEC="sudo docker exec test_container"
  matrix:
  - SUITE=buster
  - SUITE=sid
  - SUITE=stretch
  - SUITE=artful
  - SUITE=bionic
  - SUITE=xenial
  - SUITE=zesty

matrix:
  fast_finish: true
  allow_failures:
  - env: SUITE=bionic

branches:
  only:
  - master
  - release

before_install:
- sudo docker pull buildpack-deps:${SUITE}
- sudo docker images
- |
  sudo docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR} \
    buildpack-deps:${SUITE} \
    /bin/bash

install:
- ${DOCKER_EXEC} /bin/sh -c "echo \"deb [allow-insecure=yes] http://dl.bintray.com/${BINTRAY_USER}/${BINTRAY_REPO} ${SUITE} ${BINTRAY_COMPONENT}\" | tee /etc/apt/sources.list.d/bintray.list"
- ${DOCKER_EXEC} apt-get update --quiet --quiet
- ${DOCKER_EXEC} apt-get install --no-install-recommends --yes
    devscripts equivs
- ${DOCKER_EXEC} mk-build-deps
    --install --remove
    --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes --allow-unauthenticated'

script:
- if [ "${TRAVIS_PULL_REQUEST}" = false -a "${TRAVIS_BRANCH}" = release ]; then
    cat debian/changelog | awk "NR == 1 {\$2 = substr(\$2, 1, length(\$2) - 1) \"+${SUITE})\"}{print}" > debian/changelog.new;
    mv debian/changelog.new debian/changelog;
  fi
- ${DOCKER_EXEC} env WORKAROUND_BINTRAY_DEB_SUPPORT=1
    dpkg-buildpackage -i -us -uc -b -j$(nproc)

before_deploy:
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(cat debian/control | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(cat debian/changelog | head -n 1 | sed 's,.*(\(.*\)).*,\1,')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(cat debian/changelog | grep -m 1 '^ -- ' | sed 's,^.*  ,,')")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(cat debian/control | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#$(${DOCKER_EXEC} dpkg-architecture -qDEB_BUILD_ARCH)#g" | \
    tee .bintray.json
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(cat debian/control | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(cat debian/changelog | head -n 1 | sed 's,.*(\(.*\)).*,\1,')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(cat debian/changelog | grep -m 1 '^ -- ' | sed 's,^.*  ,,')")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(cat debian/control | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#all#g" | \
    tee .bintray.all.json

deploy:
- provider: bintray
  file: .bintray.json
  user: vicamo
  key:
    secure: "nCHfjRBPNpDrYCWKSQHxYQhC0+DHBAcYMwn8KLlJGXTqd0D2w3ZM4rVbXFe3tWKjkMEsXRBWrKrjU86nbWp5CMoVkiu7A5tfe8AC4bGghk0iRbMO2yeS3HmsIlW3YOpbck4zUjIlPwbgIg3uO8DuTEFGfyLfNao+WUnbUox3/5wtCMV6Ix6PW7nF++hk7kwJ34RJo9ue+GaFMt3SO/A7oIaV8Iq4xmaR5EI3h7l6r1dCiz20hdTrVrUWNcx3vyblzYmJh3mjc9tWJaj0vRJzxkDAnr3XcYPdNb6HRGpFHnfCLQgkJaElMtORUow4wJpfGb209dBhocqOpFq8xGbOHncaUqEF2H0jWWwvuIauIL58yfit5/QFkAPxGVv0QZ/66XhUR+seYNh8YGMqRTurxYFG0N06b/U2c+SJcs4KpEIfWVugP2CkV9GSDTq94W4/gYuPF2uLkwqFG0eipUam2TO8ljGaK+SpumVq0Pv8MwuS0lBjfiIzk2iSq1aq1lQUmZYNuLRRNsXLffgQwH3XzF7j13clCZwcUsYT1I/VkKkhz6P/pk3oBwF7qyFRwKuQ8KV0QFNtRMJLPJN/kFAhuEOeHDIySvv7N9NqOcLqzXWqKUNOQ0Dhok1l7ou+b0oj6cP5jsmV6qZvG/iNNrpKlhxMT+tm5+H7FBvUw/D7YzI="
  on:
    branch: release
- provider: bintray
  file: .bintray.all.json
  user: vicamo
  key:
    secure: "nCHfjRBPNpDrYCWKSQHxYQhC0+DHBAcYMwn8KLlJGXTqd0D2w3ZM4rVbXFe3tWKjkMEsXRBWrKrjU86nbWp5CMoVkiu7A5tfe8AC4bGghk0iRbMO2yeS3HmsIlW3YOpbck4zUjIlPwbgIg3uO8DuTEFGfyLfNao+WUnbUox3/5wtCMV6Ix6PW7nF++hk7kwJ34RJo9ue+GaFMt3SO/A7oIaV8Iq4xmaR5EI3h7l6r1dCiz20hdTrVrUWNcx3vyblzYmJh3mjc9tWJaj0vRJzxkDAnr3XcYPdNb6HRGpFHnfCLQgkJaElMtORUow4wJpfGb209dBhocqOpFq8xGbOHncaUqEF2H0jWWwvuIauIL58yfit5/QFkAPxGVv0QZ/66XhUR+seYNh8YGMqRTurxYFG0N06b/U2c+SJcs4KpEIfWVugP2CkV9GSDTq94W4/gYuPF2uLkwqFG0eipUam2TO8ljGaK+SpumVq0Pv8MwuS0lBjfiIzk2iSq1aq1lQUmZYNuLRRNsXLffgQwH3XzF7j13clCZwcUsYT1I/VkKkhz6P/pk3oBwF7qyFRwKuQ8KV0QFNtRMJLPJN/kFAhuEOeHDIySvv7N9NqOcLqzXWqKUNOQ0Dhok1l7ou+b0oj6cP5jsmV6qZvG/iNNrpKlhxMT+tm5+H7FBvUw/D7YzI="
  on:
    branch: release

notifications:
  slack:
    secure: JSUmIt2Bw2SC5OOOQ0p109RcssbjuaDj+zqs5Xj058KwZ2ILn/M7jrzqRAMfD64OADRN0b8FR27Fq2KNXUfBwAUfi5U3n4yYn9j0LPXOwJ5fJnAuobxj4R+NO6RG9qppoSR22mE7DQFVAJi70bhH98NrGXCO5lmcBtVBbUxi2zgZ8H1t6Yr6Wxua01RVC6VluNoNhrh/W4FG8t6c9I847GdS1QEMmiyH3vFTttwU0bjlK9iRkfwWXoB6A49mxEbr9cJ9upi9uxyWFGSI3bcr+LEuxqvEVKC182AsjPnoQJGcTKNFVxOntiZv7QhkWrLppWKc1FwZUyH85NSJLA0X/KWUmVD0/nsE13mDYXvHndSqfBuq7SX75gXAtX8iqjZA33dTQVdFiYbUkfIsds3z3fCS2/AA78CgUv85HOdQRFTDJvEEMDcIHJO4B0OxDsMxrnwsHyE2GME0mBtqmWAENH3d6MLhwQxxpj9hSmxDnrSQvgBKUAqte2aCusnDyUehUZnbiMo+y1nIA7AATz4xhDz2UhYi17y0Rw8MctDQ3xpsqcBWMg1YiLoUVffE7EyIaXxyU6KkHHEvuwdGU2Eo02GauvpYKLJzFQ2Wv4/CrB5FKXUKVUX84p3Uce0z/EN1GW6b2MlSNU4OQKMqLRCp0lVz1liUJM8GoMdSTmu+yaw=
